version: 2.1

references:
  - &CERT_KEY certs-cache-{{ checksum "year_month" }}-{{ checksum "tools/ssl/Makefile" }}-v2

# this allows you to use CircleCI's dynamic configuration feature
setup: true

# the continuation orb is required in order to use dynamic configuration
orbs:
  continuation: circleci/continuation@0.1.2

# our defined job, and its steps
jobs:
  setup:
    executor: continuation/default
    working_directory: ~/app
    steps:
      - checkout # checkout code
      - maybe_build_certs
      - run: # run a command
          name: Generate config
          command: |
            tools/circle-generate-config.sh generated_config.yml
      - continuation/continue:
          configuration_path: generated_config.yml # use newly generated config to continue

commands:
  maybe_build_certs:
    steps:
      - run:
          name: Make year_month
          command: date "+%Y-%m" > year_month
      - restore_cache:
          name: Restore certificates
          key: *CERT_KEY
      - run:
          name: Maybe rebuild certificates if they're about to expire
          command: make certs
      - save_cache:
          name: Cache built certs
          key: *CERT_KEY
          paths:
            - ~/app/tools/ssl/ca
            - ~/app/tools/ssl/ca-clients
            - ~/app/tools/ssl/mongooseim

# our single workflow, that triggers the setup job defined above
workflows:
  setup:
    jobs:
      - setup
