name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  # required for run_common_test.erl
  KEEP_COVER_RUNNING: '1'
  SKIP_AUTO_COMPILE: 'true'

jobs:
  small_tests:
    name: small_tests on OTP ${{matrix.otp}}
    strategy:
      matrix:
        otp: ['23.0.3', '22.3']
    runs-on: ubuntu-latest
    env:
      PRESET: 'small_tests'
    steps:
      - uses: actions/checkout@v2
      - uses: ErlGang/setup-erlang@v1.0.0
        with:
          otp-version: ${{ matrix.otp }}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3
          key: rebar3-${{ hashFiles('rebar.lock') }}
      - name: create certificates
        run: make certs
      - name: run test
        run: |
          ./rebar3 compile #required for coverage reporting
          tools/travis-test.sh -p $PRESET -s true -e true
      - name: report coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_JOB_ID: ${{github.run_id}}.small_tests.${{matrix.otp}}
          DEBUG: 1
        run: |
          cp _build/test/cover/*.coverdata /tmp
          ./rebar3 coveralls send

  big_tests:
    name: ${{matrix.preset}} on OTP ${{matrix.otp}}
    strategy:
      matrix:
        preset: [internal_mnesia, odbc_mssql_mnesia, mysql_redis, riak_mnesia,
                 ldap_mnesia, elasticsearch_and_cassandra_mnesia]
        otp: ['23.0.3']
    runs-on: ubuntu-latest
    env:
      PRESET: ${{matrix.preset}}
    steps:
      - uses: actions/checkout@v2
      - uses: ErlGang/setup-erlang@v1.0.0
        with:
          otp-version: ${{matrix.otp}}
      - uses: actions/cache@v2
        with:
          path: ~/.cache/rebar3
          key: rebar3-${{ hashFiles('rebar.lock') }}
      - name: create certificates
        run: make certs
      - name: set required env variables for preset
        run: tools/gh-actions-configure-preset.sh "$PRESET"
      - if: ${{ matrix.preset == 'odbc_mssql_mnesia' }}
        run: sudo apt-get install -y tdsodbc
      - name: build releases
        run: |
          ./rebar3 compile #required for coverage reporting
          tools/build-releases.sh
      - name: build big tests
        run: tools/travis-build-tests.sh
      - name: start backends
        run: tools/travis-setup-db.sh
      - name: run test
        run: tools/travis-test.sh -p $PRESET -s false -e false
      - name: report coverage
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_JOB_ID: ${{github.run_id}}.${{matrix.preset}}.${{matrix.otp}}
        run: ./rebar3 coveralls send

  coveralls_webhook:
    needs: [big_tests, small_tests]
    runs-on: ubuntu-latest
    steps:
      - name: Finish coveralls parallel build
        env:
          REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        run: >
          curl -k "https://coveralls.io/webhook?repo_token=${REPO_TOKEN}"
          -d "payload[build_num]=${GITHUB_RUN_ID}&payload[status]=done"
